
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "helm-chart.appName" . }}-pvc
spec:
  storageClassName: kubernetes.io/aws-ebs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi